function [classes] = get_classes(imgset)
% GET_CLASSES
%
% [classes] = get_classes(imgset)

valid_sets = {'od', 'vocx', 'vocxss', 'vocxssfast', 'voc', ...
			  'vocxssquality', 'imagenet', 'bdd'};

if numel(imgset) >= 2 && strcmp(imgset(1:2), 'od')
	classes = {'airplane'; 'car'; 'horse'; 'mixed'};
elseif length(imgset) >= 4 & strcmp(imgset(1:4), 'vocx')
	classes = {'aeroplane_left'; 'aeroplane_right'; ...
	           'bicycle_left'; 'bicycle_right'; ...
	           'boat_left'; 'boat_right'; ...
	           'bus_left'; 'bus_right'; ...
	           'horse_left'; 'horse_right'; ...
	           'motorbike_left'; 'motorbike_right'; ...
	           'mixed' ...
	};
elseif numel(imgset) >= 3 && strcmp(imgset(1:3), 'voc')
	classes = { ...
		  'aeroplane'; 'bicycle'; 'bird'; 'boat'; 'bottle'; 'bus'; ...
		  'car'; 'cat'; 'chair'; 'cow'; 'diningtable'; 'dog'; ...
		  'horse'; 'motorbike'; 'person'; 'pottedplant'; 'sheep'; ...
		  'sofa'; 'train'; 'tvmonitor' ; 'mixed' ...
	};
elseif numel(imgset) >= 4 && strcmp(imgset(1:4), 'coco')
	classes = { ...
			'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck',  ...
			'boat', 'trafficlight', 'firehydrant', 'stopsign', 'parkingmeter', 'bench', 'bird', 'cat',  ...
			'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',  ...
			'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', ...
			'sportsball', 'kite', 'baseballbat', 'baseballglove', 'skateboard', 'surfboard', 'tennisracket', 'bottle',  ...
			'wineglass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',  ...
			'sandwich', 'orange', 'broccoli', 'carrot', 'hotdog', 'pizza', 'donut', 'cake',  ...
			'chair', 'couch', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tv', 'laptop',  ...
			'mouse', 'remote', 'keyboard', 'cellphone', 'microwave', 'oven', 'toaster', 'sink',  ...
			'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddybear', 'hairdrier', 'toothbrush', ...
			'mixed', ...
	};
elseif numel(imgset) >= 9 && strcmp(imgset(1:9), 'imagenet6')
	classes = {'chipmunk', 'racoon', 'rake', 'rhino', 'stoat', 'wheelchair', 'mixed'};
elseif numel(imgset) >= 3 && strcmp(imgset(1:3), 'bdd')
  classes = {'bike', 'bus', 'car', 'motor', 'person', 'rider', 'trafficlight', 'trafficsign', 'train', 'truck', 'mixed'};
else 
	fprintf("'imgset' must be one of the sets");
	fprintf(' %s', valid_sets{:});
	fprintf('\n');
	error('Invalid value of "imgset"');
end

end
